version: '3.5'

services:
  next-ssg:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-ssg
    ports:
      - '3300:3000'
    volumes:
      - .:/app
      - /app/node_modules